RosetteStore.WebUI/Models/CartIndexViewModel.cs
using RosetteStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RosetteStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

RosetteStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RosetteStore.WebUI.Models
{
    public class PagingInfo
    {
        // Кол-во товаров
        public int TotalItems { get; set; }

        // Кол-во товаров на одной странице
        public int ItemsPerPage { get; set; }

        // Номер текущей страницы
        public int CurrentPage { get; set; }

        // Общее кол-во страниц
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

RosetteStore.WebUI/Models/RosettesListViewModel.cs
using RosetteStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RosetteStore.WebUI.Models
{
    public class RosettesListViewModel
    {
        public IEnumerable<Rosette> Rosettes { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

RosetteStore.WebUI/Controllers/CartController.cs
using RosetteStore.Domain.Abstract;
using RosetteStore.Domain.Entities;
using RosetteStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RosetteStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IRosetteRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IRosetteRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToRouteResult AddToCart(Cart cart, int rosetteId, string returnUrl)
        {
            Rosette rosette = repository.Rosettes
                .FirstOrDefault(g => g.RosetteId == rosetteId);

            if (rosette != null)
            {
                cart.AddItem(rosette, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int rosetteId, string returnUrl)
        {
            Rosette rosette = repository.Rosettes
                .FirstOrDefault(g => g.RosetteId == rosetteId);

            if (rosette != null)
            {
                cart.RemoveLine(rosette);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
    }
}

RosetteStore.WebUI/Controllers/NavController.cs
using RosetteStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RosetteStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IRosetteRepository repository;

        public NavController(IRosetteRepository repository)
        {
            this.repository = repository;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Rosettes
                .Select(rosette => rosette.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

RosetteStore.WebUI/Controllers/RosetteController.cs
using RosetteStore.Domain.Abstract;
using RosetteStore.Domain.Concrete;
using RosetteStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RosetteStore.WebUI.Controllers
{
    public class RosetteController : Controller
    {
        private IRosetteRepository repository;
        public int pageSize = 4;

        public RosetteController(IRosetteRepository repository)
        {
            this.repository = repository;
        }

        EFDbContext db = new EFDbContext();

        // GET: Rosette
        public ViewResult List(string category, int page = 1)
        {
            RosettesListViewModel model = new RosettesListViewModel
            {
                Rosettes = repository.Rosettes
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(rozette => rozette.RosetteId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ? 
                    repository.Rosettes.Count() :
                    repository.Rosettes.Where(rosette => rosette.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
    }
}
}

RosetteStore.WebUI/Views/Cart/Checkout.cshtml
@model RosetteStore.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Форма заказа";
}

<h2>Оформить заказ сейчас</h2>
<p>Пожалуйста введи ваши контактные данные, и мы сразу отправим товар!</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary();
    <h3>Данные</h3>
    <div class="form-group">
        <label>Ваше имя:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>

    <h3>Адрес доставки</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }


    <h3>Опции</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Использовать подарочную упаковку?
        </label>
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Обработать заказ" />
    </div>
}

RosetteStore.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Заказ обработан";
}

<h2>Спасибо!</h2>
<p>Спасибо за выбор нашего магазина. Заказ в кратчайшие сроки будет отправлен в службу доставки.</p>

RosetteStore.WebUI/Views/Cart/Index.cshtml
@model RosetteStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "GameStore: ваша корзина";
}

<h2>Ваша корзина</h2>
<table class="table">
    <thead>
        <tr>
            <th>Кол-во</th>
            <th>Товар</th>
            <th class="text-right">Цена</th>
            <th class="text-right">Общая цена</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Rosette.Name</td>
                <td class="text-right">@line.Rosette.Price.ToString("# руб")</td>
                <td class="text-right">
                    @((line.Quantity * line.Rosette.Price).ToString("# руб"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart","Cart"))
                    {
                        @Html.Hidden("RosetteId", line.Rosette.RosetteId)
                        @Html.HiddenFor(x => x.ReturnUrl);
                        <input class="btn btn-sm btn-warning" type="submit" value="Удалить">
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# руб")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
    @Html.ActionLink("Оформить заказ", "Checkout", null, new { @class = "btn btn-primary" })
</div>

RosetteStore.WebUI/Views/Cart/Summary.cshtml
@model RosetteStore.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Заказать", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-text navbar-right">
    <b>Ваша корзина:</b>
    @Model.Lines.Sum(x => x.Quantity) товаров,
    @Model.ComputeTotalValue().ToString("# руб")
</div>

RosetteStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Домой", "List", "Rosette", null,
    new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
    {
        controller = "Rosette",
        action = "List",
        category = link,
        page = 1
    }, new
    {
        @class = "btn btn-block btn-default btn-lg"
            + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
    })
}

RosetteStore.WebUI/Views/Rosette/List.cshtml
@using RosetteStore.WebUI.Models
@model RosettesListViewModel

@{
    ViewBag.Title = "Товары";
}

@foreach (var p in @Model.Rosettes)
{
    @Html.Partial("RosetteSummary", p)
}
<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List",
    new { page = x, category = Model.CurrentCategory }))
</div>

RosetteStore.WebUI/Views/Shared/RosetteSummary.cshtml
@model RosetteStore.Domain.Entities.Rosette

    <div class="well">
        <h3>
            <strong>@Model.Name</strong>
            <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
        </h3>
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="pull-right">
                @Html.HiddenFor(x => x.RosetteId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Добавить в корзину" />
            </div>
        }
        <span class="lead">@Model.Description</span>
    </div>

RosetteStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand info " href="#">RosetteStore - магазин розеток</a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>